- name: Import Elastic GPG Key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Elastic Repo into source list
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_repo_version }}/debian stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch
  apt: name={{ elasticsearch_pkg }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  notify: restart elasticsearch

- include: plugins.yml
  when: elasticsearch_with_plugin == 'yes'

- name: Configuring Elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: restart elasticsearch
