logstash_repo_version: 2.0
logstash_listen_port: 5043
logstash_redis_host: localhost
logstash_redis_port: 6379
logstash_redis_db: 0
logstash_redis_key: logstash
logstash_redis_data_type: pattern_channel 

logstash_role: indexer # indexer or shipper

# indexer
logstash_elasticsearch_hosts: '["localhost:9300"]'
logstash_elasticsearch_index: 'logstash-%{+YYYY.MM.dd}'

ssl_cert_directory: /etc/pki/tls/certs
ssl_cert: logstash-forwarder.crt
ssl_key: logstash-forwarder.key

apt_cache_valid_time: 600 # seconds between "apt-get update" calls.
